contact_links:
  - name: BUildless Discussions
    url: https://github.com/buildless/discussions
    about: Ask questions about Elide on Github
  - name: Buildless Discord
    url: https://elide.dev/discord
    about: Join the conversation on Discord
  - name: Stack Overflow
    url: https://stackoverflow.com/tags/buildless
    about: Ask questions on Stack Overflow
